AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Cars API

###############################################################################
### Conditions
###############################################################################
Conditions:
  Never: !Equals [a,b]

###############################################################################
### Output
###############################################################################
Outputs:
  URL:
    Description: "API Gateway origin endpoint URL"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"

###############################################################################
### Resources
###############################################################################
Resources:

  NullResource:
    Condition: Never
    Type: Custom::Null
    Properties:
      ServiceToken: ''

