AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Car API

###############################################################################
### Output
###############################################################################
Outputs:
  URL:
    Description: "API Gateway origin endpoint URL"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"

###############################################################################
### Resources
###############################################################################
Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: "tsv-bdx-demo-cars"
      StageName: "dev"
      TracingEnabled: true

  ListCarsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "List all cars"
      CodeUri: src/main/
      Handler: handler.cars_handler.list_cars
      Runtime: python3.7
      FunctionName: "tsv-bdx-demo-list-cars"
      Timeout: 30
      MemorySize: 128
      Tracing: Active
      Environment:
        Variables:
          TABLE: !Ref Table
      Events:
        Get:
          Type: Api
          Properties:
            Path: /cars
            Method: GET
            RestApiId: !Ref Api
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table

  GetCarFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get car by id"
      CodeUri: src/main/
      Handler: handler.cars_handler.get_car
      Runtime: python3.7
      FunctionName: "tsv-bdx-demo-get-car"
      Timeout: 30
      MemorySize: 128
      Tracing: Active
      Environment:
        Variables:
          TABLE: !Ref Table
      Events:
        Get:
          Type: Api
          Properties:
            Path: /cars/car/{id}
            Method: GET
            RestApiId: !Ref Api
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table

  ListBucketFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "List all objects inside cars bucket"
      CodeUri: src/main/
      Handler: handler.cars_handler.list_bucket
      Runtime: python3.7
      FunctionName: "tsv-bdx-demo-list-cars-files"
      Timeout: 30
      MemorySize: 128
      Tracing: Active
      Environment:
        Variables:
          BUCKET: !Ref Bucket
      Events:
        Get:
          Type: Api
          Properties:
            Path: /cars/files
            Method: GET
            RestApiId: !Ref Api
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref Bucket

  Bucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "tsv-bdx-demo-cars"

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: "tsv-bdx-demo-cars"


